name: CI/CD AstraNova

on:
  push:
    branches: [ master, main, develop, release/* ]
  pull_request:
    branches: [ master, main ]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install system dependencies (for Iced)
      run: |
        sudo apt-get update
        sudo apt-get install -y libxkbcommon-dev libwayland-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Check formatting
      run: cargo fmt -- --check
    
    - name: Run clippy
      run: cargo clippy -- -D warnings

  # Build simple binaries (para desarrollo en main/develop)
  build-binaries:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    needs: test
    if: |
      (github.event_name == 'push' && 
       (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')) ||
      github.event_name == 'pull_request'
    strategy:
      fail-fast: false # No cancelar otros jobs si uno falla
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: macos-apple-silicon

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxkbcommon-dev libwayland-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build release
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Package binary (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        tar -czf ../../../astranova-client-${{ matrix.name }}-binary.tar.gz astranova-client
    
    - name: Package binary (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        7z a ../../../astranova-client-${{ matrix.name }}-binary.zip astranova-client.exe
    
    - name: Upload binary artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.name }}
        path: |
          astranova-client-*-binary.tar.gz
          astranova-client-*-binary.zip

  # Build native packages (para ramas release/* y releases oficiales)
  build-packages:
    name: Build Native Packages
    runs-on: ${{ matrix.os }}
    needs: test
    if: |
      github.event_name == 'release' ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/'))
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-bundle
      run: cargo install cargo-bundle

    # --- FIX PARA WINDOWS ---
    - name: Install WiX Toolset and Add to PATH (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install wixtoolset -y
        # A침ade la ruta por defecto de WiX al PATH del workflow
        echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh # Usar powershell para este paso

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxkbcommon-dev libwayland-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev build-essential
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-bundle-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build native package
      # Unificamos el paso de build, ya que el comando es el mismo
      # El flag --verbose nos dar치 m치s informaci칩n si algo falla
      run: cargo bundle --release --verbose
    
    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ matrix.name }}
        path: |
          target/release/bundle/deb/*.deb
          target/release/bundle/rpm/*.rpm
          target/release/bundle/osx/*.app.tgz
          target/release/bundle/msi/*.msi
        if-no-files-found: ignore

  # Upload a release solo cuando hay packages
  upload-release:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: [build-packages]
    if: github.event_name == 'release'
    steps:
    - name: Download all package artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*

  # Upload artifacts para ramas release/* (pre-release)
  upload-prerelease:
    name: Upload Pre-release Artifacts
    runs-on: ubuntu-latest
    needs: [build-packages]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')
    steps:
    - name: Download all package artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Get branch name
      id: get_branch
      run: echo "name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
    
    - name: Create pre-release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: pre-${{ steps.get_branch.outputs.name }}-${{ github.sha }}
        name: "Pre-release: ${{ steps.get_branch.outputs.name }}"
        prerelease: true
        files: artifacts/**/*
